run:
  timeout: 5m
  tests: false
linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/rocketbitz/libfabric-go
  revive:
    rules:
      - name: exported
        disabled: true
issues:
  exclude-use-default: false
  max-same-issues: 3
  max-issues-per-linter: 0
  max-issues-per-run: 0
  exclude-dirs:
    - vendor
linters:
  enable:
    - govet
    - gofmt
    - goimports
    - revive
