version: 2
run:
  timeout: 5m
  tests: false
linters:
  enable:
    - errcheck
    - govet
    - revive
linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/rocketbitz/libfabric-go
issues:
  max-issues-per-linter: 0
  max-same-issues: 3
